version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: damilola
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
        ADMINER_DEFAULT_SEVERAL: db
   
   
  proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - '8090:81'
      # - '80:80"
      - '443:443'
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
      - ./conf_files:/conf_files
      - ./entrypoint.sh:/entrypoint.sh
    
   # command: ["/bin/bash", "-c", "chmod +x /entrypoint.sh && /entrypoint.sh"]


volumes:
  postgres_data:

