version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: damilola
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - "8090:81"
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
      - ./conf_files:/conf_files
      - ./entrypoint.sh:/entrypoint.sh
    # command: ["/bin/bash", "-c", "chmod +x /entrypoint.sh && /entrypoint.sh"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  db_data:

